export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';
export const SET_SUGGESTION_LIST = 'SET_SUGGESTION_LIST';
export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';
export const CLEAR_SELECTED_MOVIE = 'CLEAR_SELECTED_MOVIE';
export const ERROR = 'ERROR';
export const LOADING = 'LOADING';
