const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';
const SET_SUGGESTION_LIST = 'SET_SUGGESTION_LIST';
const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';
const CLEAR_SELECTED_MOVIE = 'CLEAR_SELECTED_MOVIE';
const ERROR = 'ERROR';
const LOADING = 'LOADING';
export default {
  SET_CATEGORY_LIST,
  SET_SELECTED_MOVIE,
  SET_SUGGESTION_LIST,
  CLEAR_SELECTED_MOVIE,
  ERROR,
  LOADING,
};
